name: "Build pull request"
on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "bin/**"
jobs:
  tests:
    name: "Build ${{ matrix.target }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: desktop

    steps:
      - name: Create Nix mount point
        run: sudo mkdir /nix

      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
          build-mount-path: "/nix"
          overprovision-lvm: true

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v18
        with:
          install_url: https://releases.nixos.org/nix/nix-2.5.1/install
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Setup cachix
        uses: cachix/cachix-action@v12
        with:
          name: oberblastmeister-dotfiles
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          # add binary cache through cachix name
          extraPullNames: nix-community 

      - name: Set full target
        run: |
          echo "target=nixosConfigurations.${{ matrix.target }}.config.system.build.toplevel" >> $GITHUB_ENV

      - name: Build target
        run: |
          nix build .#${{ env.target }} --fallback --show-trace -v --log-format raw

      - name: Fetch old system to profile
        run: nix build "github:oberblastmeister/dotfiles#${{ env.target }}" -v --log-format raw --profile ./profile --show-trace --no-write-lock-file

      - name: Add new system to profile
        run: nix build .#${{ env.target }} -v --log-format raw --profile ./profile

      - name: Diff profile
        id: diff
        run: |
          diff="$(nix profile diff-closures --profile ./profile)"
          echo "$diff"
          echo "::set-output name=diff::$diff"

      - name: Comment PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: ".#${{ env.target }}"
          message: |
            ### Diff of `${{ env.target }}`

            ```
            ${{ steps.diff.outputs.diff }}
            ```
