# https://github.com/sandhose/nixconf/blob/055de30/.github/workflows/update.yaml
name: Update
on:
  # Manual triggering
  workflow_dispatch:

  # Every Sunday at 12:00
  schedule:
    - cron: "0 5 * * SUN"

jobs:
  flake-update:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install nix
        uses: cachix/install-nix-action@v17
        with:
          install_url: https://releases.nixos.org/nix/nix-2.5.1/install
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Setup Git author
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'noreply@github.com'

      - name: Update lock file
        run: nix flake update --commit-lock-file

      - name: Get commit message
        id: commit
        run: |
          message="$(git log -1 --pretty=%B)"
          message="```\n$message\n```"
          message="$(echo -e $message)"
          echo "::set-output name=message::$message"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          # needed so that this triggers further workflows. not ideal.
          token: ${{ secrets.PAT }}
          title: "chore(flake): Automatic flake update"
          body: |
            ### Flake commit message

            ```
            "${{ steps.commit.outputs.message }}"
            ```
          branch: "chore/flake-update"
          delete-branch: true
